import type { MasterConfig } from "@/features/master-data/types";

export const masterDataConfigs: MasterConfig[] = [
  {
    slug: "kota",
    title: "Data Kota",
    description: "Master kota asal, tujuan, dan alamat customer.",
    tableName: "kota",
    codeField: "kode_kota",
    fields: [
      { name: "kode_kota", label: "Kode Kota", type: "text", required: true, table: true },
      { name: "nama_kota", label: "Nama Kota", type: "text", required: true, table: true },
      { name: "provinsi", label: "Provinsi", type: "text", required: true, table: true },
      { name: "kode_pos", label: "Kode Pos", type: "text", table: true },
      { name: "aktif", label: "Status Aktif", type: "boolean", table: true },
    ],
  },
  {
    slug: "pelanggan",
    title: "Data Pelanggan",
    description: "Master customer atau UMKM pengirim barang.",
    tableName: "pelanggan",
    codeField: "kode_pelanggan",
    fields: [
      { name: "pengguna_id", label: "Akun Login Customer", type: "select", relation: "pengguna_customer" },
      { name: "kota_id", label: "Kota", type: "select", relation: "kota", table: true },
      { name: "kode_pelanggan", label: "Kode Pelanggan", type: "text", required: true, table: true },
      { name: "nama_perusahaan", label: "Nama Perusahaan", type: "text", table: true },
      { name: "nama_kontak", label: "Nama Kontak", type: "text", required: true, table: true },
      { name: "telepon", label: "Telepon", type: "text", table: true },
      { name: "email", label: "Email", type: "email", table: true },
      { name: "alamat", label: "Alamat", type: "textarea" },
      { name: "aktif", label: "Status Aktif", type: "boolean", table: true },
    ],
  },
  {
    slug: "kurir",
    title: "Data Kurir",
    description: "Master kurir atau driver pengiriman darat.",
    tableName: "kurir",
    codeField: "kode_kurir",
    fields: [
      { name: "pengguna_id", label: "Akun Login Kurir", type: "select", relation: "pengguna_courier" },
      { name: "kode_kurir", label: "Kode Kurir", type: "text", required: true, table: true },
      { name: "nama_kurir", label: "Nama Kurir", type: "text", required: true, table: true },
      { name: "telepon", label: "Telepon", type: "text", table: true },
      { name: "no_sim", label: "Nomor SIM", type: "text", table: true },
      { name: "alamat", label: "Alamat", type: "textarea" },
      { name: "aktif", label: "Status Aktif", type: "boolean", table: true },
    ],
  },
  {
    slug: "kendaraan",
    title: "Data Kendaraan",
    description: "Master kendaraan dan kapasitas armada trucking.",
    tableName: "kendaraan",
    codeField: "kode_kendaraan",
    fields: [
      { name: "kode_kendaraan", label: "Kode Kendaraan", type: "text", required: true, table: true },
      { name: "no_polisi", label: "Nomor Polisi", type: "text", required: true, table: true },
      { name: "jenis_kendaraan", label: "Jenis Kendaraan", type: "text", required: true, table: true },
      { name: "merek", label: "Merek", type: "text", table: true },
      { name: "model", label: "Model", type: "text" },
      { name: "kapasitas_kg", label: "Kapasitas KG", type: "number", table: true },
      { name: "kapasitas_volume", label: "Kapasitas Volume", type: "number" },
      { name: "aktif", label: "Status Aktif", type: "boolean", table: true },
    ],
  },
  {
    slug: "jenis-pengiriman",
    title: "Data Jenis Pengiriman",
    description: "Master layanan seperti Reguler, Express, dan Cargo Besar.",
    tableName: "jenis_pengiriman",
    codeField: "kode_jenis",
    fields: [
      { name: "kode_jenis", label: "Kode Jenis", type: "text", required: true, table: true },
      { name: "nama_jenis", label: "Nama Jenis", type: "text", required: true, table: true },
      { name: "deskripsi", label: "Deskripsi", type: "textarea", table: true },
      { name: "estimasi_hari", label: "Estimasi Hari", type: "number", table: true },
      { name: "aktif", label: "Status Aktif", type: "boolean", table: true },
    ],
  },
  {
    slug: "tarif-pengiriman",
    title: "Data Tarif Pengiriman",
    description: "Master tarif berdasarkan rute kota dan jenis layanan.",
    tableName: "tarif_pengiriman",
    codeField: "harga_dasar",
    fields: [
      { name: "kota_asal_id", label: "Kota Asal", type: "select", relation: "kota", required: true, table: true },
      { name: "kota_tujuan_id", label: "Kota Tujuan", type: "select", relation: "kota", required: true, table: true },
      { name: "jenis_pengiriman_id", label: "Jenis Pengiriman", type: "select", relation: "jenis_pengiriman", required: true, table: true },
      { name: "harga_dasar", label: "Harga Dasar", type: "money", required: true, table: true },
      { name: "harga_per_kg", label: "Harga per KG", type: "money", required: true, table: true },
      { name: "berat_minimum_kg", label: "Berat Minimum KG", type: "number", required: true, table: true },
      { name: "aktif", label: "Status Aktif", type: "boolean", table: true },
    ],
  },
  {
    slug: "barang",
    title: "Data Barang",
    description: "Master jenis barang",
    tableName: "barang",
    codeField: "kode_barang",
    fields: [
      { name: "kode_barang", label: "Kode Barang", type: "text", required: true, table: true },
      { name: "nama_barang", label: "Nama Barang", type: "text", required: true, table: true },
      { name: "kategori", label: "Kategori", type: "text", table: true },
      { name: "deskripsi", label: "Deskripsi", type: "textarea" },
      { name: "berat_default_kg", label: "Berat Default KG", type: "number", table: true },
      { name: "mudah_pecah", label: "Mudah Pecah", type: "boolean", table: true },
      { name: "aktif", label: "Status Aktif", type: "boolean", table: true },
    ],
  },
];

export function getMasterConfig(slug: string) {
  return masterDataConfigs.find((config) => config.slug === slug) ?? null;
}
